In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('titanic.csv')
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [3]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [4]:
input = df.drop('Survived',axis='columns')
target = df.Survived

In [5]:
dummies = pd.get_dummies(input.Sex)
dummies.head(3)

female   male
0   False   True
1    True  False
2    True  False

In [6]:
input = pd.concat([input,dummies],axis='columns')
input.head(3)

Pclass     Sex   Age     Fare  female   male
0       3    male  22.0   7.2500   False   True
1       1  female  38.0  71.2833    True  False
2       3  female  26.0   7.9250    True  False

In [7]:
input.drop(['Sex','male'],axis='columns',inplace=True)
input.head(3)

Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True

In [8]:
input.columns[input.isna().any()]

Index(['Age'], dtype='object')

In [9]:
input.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [11]:
input.Age = input.Age.fillna(input.Age.mean())
input.head()

Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True
3       1  35.0  53.1000    True
4       3  35.0   8.0500   False

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(input,target,test_size=0.3)

In [13]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [14]:
model.fit(X_train,y_train)

GaussianNB()

In [15]:
model.score(X_test,y_test)

0.7611940298507462

In [16]:
X_test[0:10]

Pclass        Age      Fare  female
55        1  29.699118   35.5000   False
695       2  52.000000   13.5000   False
393       1  23.000000  113.2750    True
63        3   4.000000   27.9000   False
415       3  29.699118    8.0500    True
588       3  22.000000    8.0500   False
838       3  32.000000   56.4958   False
591       1  52.000000   78.2667    True
626       2  57.000000   12.3500   False
254       3  41.000000   20.2125    True

In [17]:
y_test[0:10]

55     1
695    0
393    1
63     0
415    0
588    0
838    1
591    1
626    0
254    0
Name: Survived, dtype: int64

In [18]:
model.predict(X_test[0:10])

array([0, 0, 1, 0, 1, 0, 0, 1, 0, 1])

In [19]:
model.predict_proba(X_test[:10])

array([[0.77118508, 0.22881492],
       [0.9336418 , 0.0663582 ],
       [0.00111987, 0.99888013],
       [0.95041501, 0.04958499],
       [0.47984976, 0.52015024],
       [0.97120448, 0.02879552],
       [0.94796471, 0.05203529],
       [0.01401148, 0.98598852],
       [0.92554723, 0.07445277],
       [0.487294  , 0.512706  ]])

In [20]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.728     , 0.76      , 0.776     , 0.77419355, 0.81451613])